# Generated by Django 3.1.7 on 2021-03-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.department'),
        ),
    ]
