# Generated by Django 3.1.7 on 2021-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210319_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='department',
        ),
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.ManyToManyField(null=True, to='products.Department'),
        ),
    ]
