# Generated by Django 3.1.7 on 2021-03-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210319_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='department',
            field=models.ManyToManyField(to='products.Department'),
        ),
    ]
